export const scheduleConfig = [
  {
    id: "1",
    time: "8:30",
    period: "AM",
    content: "Check-in & Welcome Kit Distribution",
  },
  {
    id: "2",
    time: "9:00",
    period: "AM",
    content: "Light Breakfast & Ice Breaker",
  },
  {
    id: "3",
    time: "10:00",
    period: "AM",
    content: "Opening Ceremony",
  },
  {
    id: "4",
    time: "10:30",
    period: "AM",
    content: "Hacking Begins",
  },
  {
    id: "5",
    time: "11:00",
    period: "AM",
    content: "Team Building Event",
  },
  {
    id: "6",
    time: "1:30",
    period: "PM",
    content: "Lunch",
  },
  {
    id: "7",
    time: "3:30",
    period: "PM",
    content: "Speaker Session 1",
  },
  {
    id: "8",
    time: "5:30",
    period: "PM",
    content: "Speaker Session 2",
  },
  {
    id: "9",
    time: "6:00",
    period: "PM",
    content: "Github Mini Event",
  },
  {
    id: "10",
    time: "8:30",
    period: "PM",
    content: "Dinner",
  },
  {
    id: "11",
    time: "9:30",
    period: "PM",
    content: "Mini Events",
  },
  {
    id: "12",
    time: "8:00",
    period: "AM",
    content: "Breakfast",
  },
  {
    id: "13",
    time: "10:30",
    period: "AM",
    content: "Submissions Due (submissions soft deadline)",
  },
  {
    id: "14",
    time: "11:30",
    period: "AM",
    content: "Hacking Ends (submissions hard deadline)",
  },
  {
    id: "15",
    time: "12:00",
    period: "PM",
    content: "Lunch",
  },
  {
    id: "16",
    time: "12:30",
    period: "PM",
    content: "Judging Starts",
  },
  {
    id: "17",
    time: "2:45",
    period: "PM",
    content: "Closing Ceremony",
  },
];
